### ISSUE TITLE
[iOS] Not showing notification banner when app running in Background

### ISSUE THREAD

**Issue by ashwinpreet** [evollu/react-native-fcm#15]
@evollu I have created a React Native Project and added the "react-native-fcm" for the Push Notification Support. In android i am able to run the app as expected.

But in iOS, if the app is in foreground, I am getting the notification(I have added some console.log in the "notification" event). But when I push the app background then I am not able to see the **notification Banner.** 

Is I am missing anything?

**Comment by evollu** [comment]
APN sometimes delay the notification to save battery. Try add `priority: 'high'` into payload

**Comment by ashwinpreet** [comment]
@evollu May be I am sending the Payload in the wrong format. Can you share me the sample format of the message.
I am using FCM console to send the message.

**Comment by evollu** [comment]
post to `https://fcm.googleapis.com/fcm/send`
```
{
"to":"some_device_token",
  "content_available": true,
  "notification": {
      "title": "hello",
      "body": "yo",
      "click_action": "fcm.ACTION.HELLO"
  },
  "data": {
      "extra":"juice"
  },
  "priority": "high"
}
```

**Comment by ashwinpreet** [comment]
I am trying from Firebase console to send message. Following is the format I am using for sending the message. Is I am missing anything.

<img width="700" alt="screen shot 2016-06-19 at 1 03 30 am" src="https://cloud.githubusercontent.com/assets/1861729/16173272/b87fddb8-35b9-11e6-9a75-efd93fd1fd8b.png">

**Comment by evollu** [comment]
firebase console is limiting and I experienced some delay sometime too. Try to send with postman?
Also does app receive notification when it is killed?

**Comment by ashwinpreet** [comment]
Thanks @evollu. Issue is resolved now.

I was not using the proper certificate.

**Comment by first350** [comment]
@ashwinpreet I am currently facing the same issue, can you describe your situation in more detail ?
I double checked my certificate but the banner still not showing. Any help will be appreciated.

**Comment by SujitNachan** [comment]
Thanks @evollu and @ashwinpreet. Issue is resolved now.
I miss this code .
"notification": {
      "title": "hello",
      "body": "yo",
      "click_action": "fcm.ACTION.HELLO"
  },`

**Comment by NawazKhanMd** [comment]
I am geting a callback in my code when I recieve a push notification, but when in background i cant see the banner or any any kind or notification that push notification has beeen recieved.
