### ISSUE TITLE
FCM.getInitialNotification() causes app to crash on iOS

### ISSUE THREAD

**Issue by ghuh** [evollu/react-native-fcm#157]
When calling FCM.getInitialNotification() and there actually is a notification, I get the following error
![simulator screen shot oct 13 2016 8 07 50 pm](https://cloud.githubusercontent.com/assets/7354238/19373384/c9ed9a22-9180-11e6-92fa-f1a4ed5521cf.png)
on iPhone 7 iOS 10 simulator.  If the app was not opened by a notification, then there is no crash.  This all works as expected, both with and without being opened by notification, on Android 7.0 simulator.

**Comment by evollu** [comment]
can you share your notification payload?

**Comment by ghuh** [comment]
```javascript
FCM.scheduleLocalNotification({
    fire_date: fireDate,
    body: "",
    sound: "",
    id: "",
    pathToOpen: "",
});
```

**Comment by evollu** [comment]
that is so tricky, id with empty string?

**Comment by evollu** [comment]
you should get id is required error immediately, are you using the latest version?

**Comment by ghuh** [comment]
Sorry, none of those are actually empty.  I pulled out the values because they are specific to my application.  I was just trying to show what keys and what value types.

**Comment by evollu** [comment]
can you show me the payload with content? Looks like the JSON parsing failed

**Comment by ghuh** [comment]
Here is an example that reproduces the problem:

```javascript
        FCM.scheduleLocalNotification(
            {
                fire_date: fireDate,
                body: "body!",
                sound: "default",
                id: "id09823452",
                pathToOpen: "page1/page2",
            }
        );
```

**Comment by ghuh** [comment]
Any thoughts on why that particular payload would cause an error?  It looks to be standard JSON to me.

**Comment by evollu** [comment]
could it be the type of time? it should be unix time stamp
i'm on vacation so don't have access to the code to test

**Comment by ghuh** [comment]
Nope, that is not the problem.  You can stick any standard unix time stamp in there and it will reproduce the issue.

**Comment by raffij** [comment]
I've been having this issue too. Reverted to the standard notification code for now.

**Comment by raffij** [comment]
Looks like the error might have been fixed yesterday in React Native core.

https://github.com/facebook/react-native/commit/5a3dbdfbcd66522bfda518555e2c325145c7d283

**Comment by sibelius** [comment]
@ghuh have u solved ur issue?

**Comment by ghuh** [comment]
No. Last time I tried it, it was still broken and I haven't had a chance to dig into it deeper.

**Comment by raffij** [comment]
@ghuh did you update to the latest react-native? as the error you were observing was react-native not passing the original error to javascript correctly i think.

**Comment by evollu** [comment]
this issue should be solved in latest version

**Comment by ghuh** [comment]
I had at the time, but it's been a few weeks since I've tried it.  If you've tried it and it works for you, feel free to close this ticket.  I can re-open it again if needed.

**Comment by ghuh** [comment]
I have confirmed that this is fixed in RN v0.40.0
