### ISSUE TITLE
FCM.presentLocalNotification not working on iOS

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-fcm#226]
rn 39.2
rn-fcm: 2.5.2
iOS 10.1

The below method is not working on iOS 10.1, it does not show a local notification when the app is in foreground:

```objective-c
RCT_EXPORT_METHOD(presentLocalNotification:(id)data resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
{
  if([UNUserNotificationCenter currentNotificationCenter] != nil){
    UNNotificationRequest* request = [RCTConvert UNNotificationRequest:data];
    [[UNUserNotificationCenter currentNotificationCenter] addNotificationRequest:request withCompletionHandler:^(NSError * _Nullable error) {
      if (!error) {
        resolve(nil);
      }else{
        reject(@"notification_error", @"Failed to present local notificaton", error);
      }
    }];
  }else{
    UILocalNotification* notif = [RCTConvert UILocalNotification:data];
    [RCTSharedApplication() presentLocalNotificationNow:notif];
    resolve(nil);
  }
}
```

However if I go back to the older code that it is only:

```
    UILocalNotification* notif = [RCTConvert UILocalNotification:data];
    [RCTSharedApplication() presentLocalNotificationNow:notif];
    resolve(nil);

```

it works fine

how can I add logs on native code to debug properly this? or add a breaking point?

cc @MechanicKim had the same issue

**Comment by sibelius** [comment]
I've added some logs on the code

RCTLogWarn(@"PPP %@", [UNUserNotificationCenter currentNotificationCenter]);

RCTLogWarn(@"PPP1: %@", data);
RCTLogWarn(@"PPP2: %@", request);

I've noticed that request has the following format:

```jsx
YellowBox.js:69 PPP2: <UNNotificationRequest: 0x17422aea0; identifier: 1481659752360, content: <UNNotificationContent: 0x1742e3d00; title: (null), subtitle: (null), body: Blue comentou no seu post: "Lucas ", categoryIdentifier: brandlovers.LIKE, launchImageName: , peopleIdentifiers: (
), threadIdentifier: , attachments: (
), badge: (null), sound: <UNNotificationSound: 0x1700ab6a0>, hasDefaultAction: YES, shouldAddToNotificationsList: YES, shouldAlwaysAlertWhileAppIsForeground: NO, shouldLockDevice: NO, shouldPauseMedia: NO, isSnoozeable: NO, fromSnooze: NO, darwinNotificationName: (null), darwinSnoozedNotificationName: (null), trigger: <UNCalendarNotificationTrigger: 0x17403d8c0; dateComponents: <NSDateComponents: 0x174151930>
    Calendar Year: 2016
    Month: 12
    Leap month: no
    Day: 13
    Hour: 18
    Minute: 9
    Second: 12, repeats: NO>>
```

I guess that `shouldAlwaysAlertWhileAppIsForeground: NO` should be true to be able to show the notification while the app is in foreground

**Comment by evollu** [comment]
@sibelius it is fixed in 2.5.2 please verify
where is `shouldAlwaysAlertWhileAppIsForeground`?

**Comment by sibelius** [comment]
`shouldAlwaysAlertWhileAppIsForeground` is this variable: `UNNotificationRequest* request`

result of `UNNotificationRequest* request = [RCTConvert UNNotificationRequest:data];`

**Comment by evollu** [comment]
interesting. I don't see it in my xcode intellisense. Are you sure it is an exposed property?

**Comment by sibelius** [comment]
I'm not sure

I just add a `RCTLogWarn(@"PPP2: %@", request);` to print it on chrome debug

idk if this helps

**Comment by evollu** [comment]
it could be a private property

**Comment by VinZenTz1989** [comment]
I got the same problem and tried to go back to older code.

FCM.presentLocalNotification isn't still working on iOS

**Comment by yannickoo** [comment]
I can confirm this :(

**Comment by evollu** [comment]
@VinZenTz1989 @yannickoo are you using the latest version?

**Comment by yannickoo** [comment]
@evollu yes I'm using `2.5.2`

**Comment by evollu** [comment]
what is the error message? Can you try adding id: 'some id' into payload?

**Comment by yannickoo** [comment]
I also tried it with `id` property but IIRC you added that in fb9a3bf3d9023a6b81d2e659b41026df356ad260 😕

One question I always had: Where could I find a correct implementation in `AppDelegate.m` because I saw different implementations and the code from the `README.md` seems to be incomplete because things like settings the APNS token or telling Firebase that user opened notification is missing.
Is there chance that local notifications could not work because there is some code missing in `AppDelegate.m`?

**Comment by evollu** [comment]
read me is correct. Setting APNS token is done by FCM SDK automatically. 
Are you seeing local notification not showing up or red screen?

**Comment by yannickoo** [comment]
No red screen there is just no change in the UI.

**Comment by evollu** [comment]
fixed in 2.5.3

**Comment by yannickoo** [comment]
@evollu I guess this should be enough right? Still not seeing local notifications in foreground :(

```js
FCM.presentLocalNotification({
  body: 'body',
  show_in_foreground: true
})
```

**Comment by evollu** [comment]
have you rebuilt ios?

**Comment by yannickoo** [comment]
Wow nice I could get a local notification! Unfortunately it's not showing up when adding `sound` property.

**Comment by evollu** [comment]
what sound value are you passing

**Comment by yannickoo** [comment]
I tried `notification` and `notification.wav` (one of them worked in the past) and the audio file is properly referenced in `Ressources`.

**Comment by evollu** [comment]
is there any error in xcode log?

**Comment by yannickoo** [comment]
There is only `<FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"` but this shouldn't be relevant for this issue.

**Comment by evollu** [comment]
does it work if you comment out line 250-259

**Comment by yannickoo** [comment]
Magic :dizzy: I can hear the custom notification sound again :)

**Comment by evollu** [comment]
ok so it works for old API but not new one?

**Comment by yannickoo** [comment]
Exactly. I'm using iOS 10.2 btw

**Comment by evollu** [comment]
there must be a way, let me check

**Comment by evollu** [comment]
can you replace line 48 with 
```
NSString* sound = [RCTConvert NSString:details[@"sound"]];
  if(sound != nil){
    content.sound = [UNNotificationSound soundNamed:sound];
  }
```

**Comment by yannickoo** [comment]
Does not work when using the current implementation at line ~250. I guess I need to switch back to your suggestion from https://github.com/evollu/react-native-fcm/issues/226#issuecomment-267678456.

**Comment by evollu** [comment]
sure you can do the work around. I will play with it myself and figure out the fix.

**Comment by evollu** [comment]
@yannickoo just played with it. works for me

**Comment by yannickoo** [comment]
Just updated the 📦 and it works!

**Comment by VinZenTz1989** [comment]
@evollu sorry for replying late.

Just updated everything works fine.

**Comment by yannickoo** [comment]
@VinZenTz1989 do you receive remote and background notifications for your app with the latest code?

**Comment by sibelius** [comment]
it does work on the latest branch, tks @evollu for the hard work

however, it is showing 2 notifications instead of just 1

**Comment by evollu** [comment]
@sibelius I don't have this issue. Do you have more detail?

**Comment by sibelius** [comment]
this is my function to handle push notification, `appLink` will go to screen based on url deeplinking
```jsx
export function handlePush(notif) {
  if (!notif) {
    return;
  }

  if(notif.local_notification) {
    //this is a local notification
    console.log('local notification: ', notif.local_notification)

    if (notif.opened_from_tray) {
      // Cancel notification
      FCM.cancelLocalNotification(notif.id);
      if (notif.url) {
        appLink(notif.url, navigator);
      }
    }

    return;
  }

  if(notif.opened_from_tray) {
    //app is open/resumed because user clicked banner
    console.log('opened_from_tray: ', notif.opened_from_tray)
    if (notif.url) {
      appLink(notif.url, navigator);
    }
    return;
  }

  const userInteraction = AppState.currentState === 'background';
  if (userInteraction) {
    if (notif.url) {
      appLink(notif.url, navigator);
    }
  } else {
    console.log('presentLocal');
    FCM.presentLocalNotification({
      id: new Date().getTime().toString(),
      title: notif.title,
      body: notif.body,
      url: notif.url,
      icon: 'ic_notification',
      large_icon: 'ic_notification',
      color: '#e34056',
      priority: 'high',
      auto_cancel: false,
      click_action: 'brandlovers.LIKE',
      show_in_foreground: true,
      // priority: "high",
    })
  }
}
```

**Comment by evollu** [comment]
If you pass show_in_foreground in push notification body, you don't need to call presentLocalNotification manually.

**Comment by sibelius** [comment]
this notification come from my backend, so I can't have `show_in_foreground` in the push notification body, because I don't know if the user will have the app opened or not, so if the app is in foreground I create a local notification from the remote notification

**Comment by evollu** [comment]
when you say you see 2 notifications, are they both remote? or one is local?

**Comment by sibelius** [comment]
A receive a remote notification that do not show up in the tray neither for the user,
this remote notification will create a local notification, after that

this line will be called twice:
`console.log('local notification: ', notif.local_notification)`

**Comment by evollu** [comment]
so it is not notification showed twice, but the callback gets called twice? are you using iOS?

**Comment by sibelius** [comment]
this only happens on ios, on android the behavior is correctly

**Comment by evollu** [comment]
can you add break point in AppDelegate.m on both onLocalNotificationReceive and willReceiveNotification? I suspect both of them are called

**Comment by yannickoo** [comment]
@evollu should we implement `willReceiveNotification`? You didn't mention it in `README` file.

**Comment by evollu** [comment]
oh I mean willPresentNotification

**Comment by sibelius** [comment]
`onLocalNotificationReceived` is `didReceiveLocalNotification` ?

**Comment by sibelius** [comment]
This is the flow when the app is on foreground on ios

- receive remote notification
- `handlePush`: localNotification: false (gcm.message_id: 0:1482235706845068%58fc5f4058fc5f40)
- calls `willPresentNotification`: `show_in_foreground` is false, so call `completionHandler(UNNotificationPresentationOptionNone);`
- `handlePush`: localNotification: false (yep, again: gcm.message_id: 0:1482235706845068%58fc5f4058fc5f40, the same as above)
- calls `willPresentNotification`: `show_in_foreground` is true, so call `completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound);`
- `handlePush`: localNotification: true
- `handlePush`: localNotification: true

I think the flow is kind of confusing, feel free to ask more information

`didReceiveLocalNotification` has not been called

**Comment by evollu** [comment]
ah, can you check if didReceiveRemoteNotification is called first?
add `if([UNUserNotificationCenter currentNotificationCenter] != nil){ return; }` in line 71 in AppDelegate.m

**Comment by stefanwuest** [comment]
I cannot get any notification to show up when the app is in foreground. When I try to present a local notification, I can log it, but no banner is shown, and nothing shows up in the Notification Center. 
I also tried to send `show_in_foreground: true` from the server, but the notification still didn't show up, when the app is running in foreground. Everything works as expected when the app is in background.

Any ideas what the issue could be?

Here's the code for the local notification:
```
FCM.presentLocalNotification({
  title: notif.title,
  body: notif.body,
  priority: "high",
  local: true,
  data: notif.data
});
```

**Comment by evollu** [comment]
@stefanwuest what is your payload on server side?

**Comment by stefanwuest** [comment]
This is my payload on the server side:
```
$fields = array(
			'to' => $deviceToken,
			'collapse_key' => 'new_message',
			'data' => [
				'custom_notification' => [
					'title' => 'Test',
					'body' => $messageTxt,
					'sound' => 'default',
					'data' => $custom,
					'show_in_foreground' => true
				]
			],
			'notification' => [
				'title' => 'Test',
				'body' => $messageTxt,
				'sound' => 'default',
				'data' => $custom,
				'show_in_foreground' => true
			]
		);
```

**Comment by MechanicKim** [comment]
I had a same experience.
But I could resolve this problem. For resolving this problem.
- Update version
- Please refer readme and fix android setting.
  Android setting for using this service has been changed.
- Test local notification!

I succeed through this process.
I hope that my recommendation will help you.

Good luck!

2017-01-05 15:14 GMT+09:00 stefanwuest <notifications@github.com>:

**Comment by evollu** [comment]
@stefanwuest are you trying to target both platform? Which platform are you having issue now?

**Comment by stefanwuest** [comment]
@evollu yes, trying to target both platforms. the problem is now on iOS when the app is in foreground. I tried your suggested payload, but still no success.
I can log the notification, but no banner showing up, and nothing is in notification center.
![image](https://cloud.githubusercontent.com/assets/5959858/21684673/539c76dc-d324-11e6-848f-a9dc8389194b.png)

**Comment by evollu** [comment]
when you are in foreground, notification are sent through FCM socket rather than APN (it is a firebase behavior), which means you need to build a local notification specifically.
To verify that, you can add break points in notification handlers in AppDelegate.m and nothing should be triggered

**Comment by stefanwuest** [comment]
I was not able to have a local notification show up (see my first post in this issue).
Here's the call for that again:
```
FCM.presentLocalNotification({
  title: notif.title,
  body: notif.body,
  priority: "high",
  local: true,
  data: notif.data
});
```

**Comment by evollu** [comment]
```
FCM.presentLocalNotification({
  title: notif.title,
  body: notif.body,
  priority: "high",
  show_in_foreground: true,
  data: notif.data
});
```

**Comment by stefanwuest** [comment]
Got it. Seems like my notif.title and notif.body was undefined. Thanks for the help!

**Comment by evollu** [comment]
aha...
@sibelius can I close this now?

**Comment by sibelius** [comment]
yep, I'll reopen if needed

**Comment by chitaranjanxelpmoc** [comment]
hey i am getting same problem

i am manually triggering  this
 ```
 FCM.presentLocalNotification({
      vibrate: 500,
      title: "Hello",
      body: "Test Notification",
      big_text: "i am large, i am large, i am large, i am large,",
      show_in_foreground: true,
      number: 10
    });
```
its working in android but not in ios why???

**Comment by evollu** [comment]
@chitaranjanxelpmoc check your notification permission
